### ISSUE TITLE
Not connecting to server

### ISSUE THREAD

**Issue by gustavosaez** [jin5354/alfred3-workflow-CurrencyConvert#27]
[15:17:30.080] Logging Started...
[15:17:37.287] Currency Convert[Script Filter] Queuing argument ''
[15:17:37.948] Currency Convert[Script Filter] Script with argv '(null)' finished
[15:17:37.951] ERROR: Currency Convert[Script Filter] Code 1: ./add.rb:12:in `<main>': undefined method `each' for nil:NilClass (NoMethodError)
[15:18:07.063] Currency Convert[Script Filter] Queuing argument ''
[15:18:07.742] Currency Convert[Script Filter] Script with argv '(null)' finished
[15:18:07.745] ERROR: Currency Convert[Script Filter] Code 1: ./convert.rb:87:in `<main>': undefined method `each' for nil:NilClass (NoMethodError)

**Comment by eplodn** [comment]
I'm seeing this issue too. Alfred 4.3.3

**Comment by jjarava** [comment]
Same here...

**Comment by topazbarziv** [comment]
> [15:17:30.080] Logging Started...
> [15:17:37.287] Currency Convert[Script Filter] Queuing argument ''
> [15:17:37.948] Currency Convert[Script Filter] Script with argv '(null)' finished
> [15:17:37.951] ERROR: Currency Convert[Script Filter] Code 1: ./add.rb:12:in `<main>': undefined method `each' for nil:NilClass (NoMethodError)
> [15:18:07.063] Currency Convert[Script Filter] Queuing argument ''
> [15:18:07.742] Currency Convert[Script Filter] Script with argv '(null)' finished
> [15:18:07.745] ERROR: Currency Convert[Script Filter] Code 1: ./convert.rb:87:in `<main>': undefined method `each' for nil:NilClass (NoMethodError)



> I'm seeing this issue too. Alfred 4.3.3



> Same here...

Check this out https://github.com/topazbarziv/alfred4-workflow-CurrencyConvert/releases

**Comment by jt196** [comment]
@topazbarziv - this seems to be happening on your fork ( Alfred 4.3.3):

```
[10:57:07.439] Logging Started...
[10:57:13.507] Currency Convert[Script Filter] Queuing argument ''
[10:57:13.827] Currency Convert[Script Filter] Script with argv '(null)' finished
[10:57:13.829] ERROR: Currency Convert[Script Filter] Code 1: ./base.rb:12:in `<main>': undefined method `each' for nil:NilClass (NoMethodError)
```

**Comment by topazbarziv** [comment]
@jt196 At Alfred v4.5.1 (Latest version) everything works great!
